### ISSUE TITLE
Terraform managed octoDNS org - heads up that this is a thing

### ISSUE THREAD

**Issue by ross** [octodns/terraformed#1]
This now manages all the repos and branch protection rules. It should keep everything setup the same way/as desired.

For now I'll just have to run it as I have a copy of the state file. I can't think of a good way to have a shared state stored somewhere for this OSS thing. Open to ideas. I haven't looked yet, but it's possible there's no secrets in the state file and it can be kept in the repo, but that still seems flakey/error prone...

From now on new repos can be added and/or access changed using terraform. I'll look at adding a system for managing repo-specific access in the near future. 

Going to close this as soon as it's opened since it's just an fyi thing

/cc @octodns/review @theojulienne @yeled fyi

**Comment by yzguy** [comment]
I think Terraform Cloud free might work, it includes state storage, locking, plan/apply etc.

https://www.hashicorp.com/products/terraform/pricing

Just 5 users limit, which probably is not a big deal, the “maintainer” circle is small. Maybe a generic like octodns email to register things with, and a private repo that uses [gopass](https://github.com/gopasspw/gopass) or [git-crypt](https://github.com/AGWA/git-crypt) to store/encrypt secrets. Repo access via normal GH controls, and GPG keys to encrypt/decrypt. Although, you might be able to create an octodns org on TF cloud with a normal account, and be apart of it, invite others, etc. Just unsure if it’s tied to a user or it’s a logical entity that includes users. This would dictate whether it would be better to have it owned by a generic octodns account versus a maintainer account.

I had no idea Terraform had a GitHub provider so this is pretty cool!

**Comment by ross** [comment]
> https://www.hashicorp.com/products/terraform/pricing

Didn't realize they had a free offering. Will check it out.
